#!/usr/bin/env node
/**
 * Vercel build step: writes dashboard/config.js from the ECONOS_KERNEL_WS_URL env var.
 *
 * If the env var is unset (e.g. local dev), writes an empty config so the dashboard
 * falls back to same-origin (`ws://<host>/ws`).
 */
const fs = require('fs');
const path = require('path');

const url = (process.env.ECONOS_KERNEL_WS_URL || '').trim();
const out = path.join(__dirname, '..', 'dashboard', 'config.js');
const body =
  '// Generated by scripts/build-config.js — do not edit by hand.\n' +
  `window.ECONOS_KERNEL_WS_URL = ${JSON.stringify(url)};\n`;

fs.writeFileSync(out, body);
console.log(`[build-config] wrote ${out}  (kernel = ${url || '(same-origin fallback)'})`);
